DROP TABLE UTIL_IPORTAL.ELG_BOOKINGS CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.ELG_BOOKINGS
(
  ID                 NUMBER,
  CUSTID             VARCHAR2(100 BYTE),
  CUSTNAME           VARCHAR2(150 BYTE),
  LOUNGEID           NUMBER,
  BOOKINGTIME        DATE,
  NUMOFPEOPLEGOWITH  NUMBER,
  RESERVATIONCODE    VARCHAR2(100 BYTE),
  VOUCHERID          NUMBER,
  BOOKINGNOTE        VARCHAR2(2000 BYTE),
  CHECKINTIME        DATE,
  FLIGHTTIKETNUM     VARCHAR2(150 BYTE),
  CHECKEDINNOTE      VARCHAR2(2000 BYTE),
  IMAGEURL           VARCHAR2(200 BYTE),
  BOOKINGSTATUSID    NUMBER,
  STATUS             VARCHAR2(100 BYTE),
  ORDERVIEW          NUMBER,
  CREATEBY           VARCHAR2(150 BYTE),
  CREATEDATE         DATE,
  LASTMODIFIEDBY     VARCHAR2(150 BYTE),
  LASTMODIFIEDDATE   DATE
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
