DROP TABLE UTIL_IPORTAL.ELG_LOG CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.ELG_LOG
(
  DATETIME   DATE,
  REF_NO     VARCHAR2(150 BYTE),
  TAG        VARCHAR2(200 BYTE),
  REQ_DATA   VARCHAR2(2000 BYTE),
  RESP_DATA  VARCHAR2(2000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
