DROP TABLE UTIL_IPORTAL.VUC_VOUCHER_AMT_CONDITIONS CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.VUC_VOUCHER_AMT_CONDITIONS
(
  ID                NUMBER,
  VOUCHERID         NUMBER,
  AMOUNTVALUATION   NUMBER,
  MINTRANSAMOUNT    NUMBER,
  MAXTRANSAMOUNT    NUMBER,
  PERCENTVALUATION  NUMBER,
  MAXAMOUNTCOUPON   NUMBER
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
