DROP TABLE UTIL_IPORTAL.VUC_ISSUE_BATCH CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.VUC_ISSUE_BATCH
(
  ID              NUMBER,
  NAME            VARCHAR2(250 BYTE),
  DESCRIPTION     VARCHAR2(500 BYTE),
  ISSUEDATE       DATE,
  EXPIREDATE      DATE,
  STATUS          VARCHAR2(30 BYTE),
  CREATEDATE      DATE,
  CREATEBY        VARCHAR2(50 BYTE),
  LASTMODIFYDATE  DATE,
  LASTMODIFYBY    VARCHAR2(50 BYTE)
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
