DROP TABLE UTIL_IPORTAL.VUC_APPLIED_CHANNEL CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.VUC_APPLIED_CHANNEL
(
  ID                NUMBER,
  NAME              VARCHAR2(250 BYTE),
  DESCRIPTION       VARCHAR2(500 BYTE),
  CHANNELCODE       VARCHAR2(50 BYTE),
  STATUS            VARCHAR2(50 BYTE),
  CREATEDBY         VARCHAR2(50 BYTE),
  CREATEDDATE       DATE,
  LASTMODIFIEDDATE  DATE,
  LASTMODIFIEDBY    VARCHAR2(50 BYTE),
  ORDERVIEW         VARCHAR2(10 BYTE)
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
