DROP TABLE UTIL_IPORTAL.ELG_CONFIGURATE CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.ELG_CONFIGURATE
(
  ID                NUMBER,
  NAME              VARCHAR2(250 BYTE),
  VALUE             INTEGER,
  DESCRIPTION       VARCHAR2(2000 BYTE),
  ORDERVIEW         INTEGER,
  CREATEBY          VARCHAR2(150 BYTE),
  CREATEDATE        DATE,
  LASTMODIFIEDBY    VARCHAR2(150 BYTE),
  LASTMODIFIEDDATE  DATE,
  STATUS            VARCHAR2(50 BYTE)
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
