DROP TABLE UTIL_IPORTAL.SRV_QUESTIONS CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.SRV_QUESTIONS
(
  ID                   NUMBER,
  NAMEVN               VARCHAR2(500 BYTE),
  NAMEEN               VARCHAR2(500 BYTE),
  CONTENTVN            VARCHAR2(1000 BYTE),
  CONTENTEN            VARCHAR2(1000 BYTE),
  INPUTTYPEID          NUMBER,
  SURVEYSECTIONID      NUMBER,
  ALLOWMULTIPLECHOICE  VARCHAR2(50 BYTE),
  MINCHOICE            NUMBER,
  MAXCHOICE            NUMBER,
  ALLOWCOMMENT         VARCHAR2(50 BYTE),
  STATUS               VARCHAR2(150 BYTE),
  ORDERVIEW            NUMBER,
  CREATEBY             VARCHAR2(150 BYTE),
  CREATEDATE           DATE,
  LASTMODIFIEDBY       VARCHAR2(150 BYTE),
  LASTMODIFIEDDATE     DATE
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
