DROP TABLE UTIL_IPORTAL.VUC_PUBLISHED_VOUCHER CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.VUC_PUBLISHED_VOUCHER
(
  ID              NUMBER,
  PINNUM          VARCHAR2(30 BYTE),
  STATUS          VARCHAR2(50 BYTE),
  VOUCHERID       NUMBER,
  COUNTUSED       NUMBER                        DEFAULT 0                     NOT NULL,
  CREATEDATE      DATE,
  CREATEBY        VARCHAR2(50 BYTE),
  LASTMODIFYDATE  DATE,
  LASTMODIFYBY    VARCHAR2(50 BYTE)
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
