DROP TABLE UTIL_IPORTAL.VUC_VOUCHER_TRANS CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.VUC_VOUCHER_TRANS
(
  ID           NUMBER,
  PINNUM       VARCHAR2(30 BYTE),
  VOUCHERCODE  VARCHAR2(50 BYTE),
  CUSTOMERID   VARCHAR2(30 BYTE),
  CHANNEL      VARCHAR2(50 BYTE),
  TRANSTYPE    VARCHAR2(50 BYTE),
  TRANSAMOUNT  NUMBER,
  TRANSREFNO   VARCHAR2(30 BYTE),
  DATETIME     VARCHAR2(30 BYTE),
  STATUS       VARCHAR2(30 BYTE)
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
