DROP TABLE UTIL_IPORTAL.ELG_CHECKIN_PEOPLE_GO_WITH CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.ELG_CHECKIN_PEOPLE_GO_WITH
(
  ID               NUMBER,
  CUSTID           VARCHAR2(150 BYTE),
  CUSTNAME         VARCHAR2(150 BYTE),
  PHONENUM         VARCHAR2(20 BYTE),
  FLIGHTTICKETNUM  VARCHAR2(150 BYTE),
  BOOKINGID        NUMBER,
  STATUS           VARCHAR2(150 BYTE)
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
