DROP TABLE UTIL_IPORTAL.SRV_OPTION_CHOICES CASCADE CONSTRAINTS;

CREATE TABLE UTIL_IPORTAL.SRV_OPTION_CHOICES
(
  ID                NUMBER,
  NAMEVN            VARCHAR2(500 BYTE),
  NAMEEN            VARCHAR2(500 BYTE),
  DESCRIPTIONVN     VARCHAR2(2000 BYTE),
  DESCRIPTIONEN     VARCHAR2(2000 BYTE),
  STATUS            VARCHAR2(150 BYTE),
  ORDERVIEW         NUMBER,
  CREATEBY          VARCHAR2(150 BYTE),
  CREATEDATE        DATE,
  LASTMODIFIEDBY    VARCHAR2(150 BYTE),
  LASTMODIFIEDDATE  DATE,
  IMAGE_URL         VARCHAR2(300 BYTE)
)
TABLESPACE PORTAL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
